platform :ios, '9.0'
inhibit_all_warnings!
use_modular_headers!

source 'https://github.com/CocoaPods/Specs.git'

target 'FXTableViewManager' do

pod 'YYKit'
pod 'MJRefresh'
pod 'Masonry'
pod 'MyLayout'
pod 'IQKeyboardManager'
pod 'SVProgressHUD'
pod 'UITextView+Placeholder'

end
